# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.building.datastruct import Tree


a = Analysis(
    ['src\\rwmod\\cli.py'],
    pathex=['src'],
    binaries=[],
    datas=[('static', 'static')],
    hiddenimports=[
        # Web UI (started via `rwmod web` → uvicorn.run("rwmod.server:app")).
        # uvicorn.run() takes a *string*, so modulegraph can't follow the
        # import chain — every module used by the web app must be listed here.
        'rwmod.server',
        'uvicorn',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        # Core modules
        'rwmod.app_state',
        'rwmod.autoupdate',
        'rwmod.backup',
        'rwmod.cache_db',
        'rwmod.compat',
        'rwmod.compatibility',
        'rwmod.config',
        'rwmod.database',
        'rwmod.deps',
        'rwmod.downloader',
        'rwmod.errors',
        'rwmod.i18n',
        'rwmod.load_order',
        'rwmod.logger',
        'rwmod.metadata',
        'rwmod.mod_cache',
        'rwmod.models',
        'rwmod.models.schemas',
        'rwmod.offline',
        'rwmod.parser',
        'rwmod.profile',
        'rwmod.queue',
        'rwmod.rimpy_db',
        'rwmod.rimsort',
        'rwmod.save_parser',
        'rwmod.skymods',
        'rwmod.steamcmd',
        'rwmod.tags',
        'rwmod.transfer',
        'rwmod.undo',
        'rwmod.utils',
        'rwmod.workshop',
        # All router modules
        'rwmod.routers.auto_update',
        'rwmod.routers.backups',
        'rwmod.routers.compat',
        'rwmod.routers.config',
        'rwmod.routers.dashboard',
        'rwmod.routers.download',
        'rwmod.routers.health',
        'rwmod.routers.history',
        'rwmod.routers.metrics',
        'rwmod.routers.mods',
        'rwmod.routers.profiles',
        'rwmod.routers.queue',
        'rwmod.routers.rimsort',
        'rwmod.routers.saves',
        'rwmod.routers.tags',
        'rwmod.routers.transfer',
        'rwmod.routers.undo',
        'rwmod.routers.workshop',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Hard-fail-safe: never pull in unrelated heavy AI/data packages even if
        # a build is accidentally run against a global Python that has them.
        # rwmod only needs fastapi/pydantic/typer/uvicorn.
        'torch',
        'torchvision',
        'cv2',
        'polars',
        'numpy',
        'scipy',
        'pandas',
        'sklearn',
        'scikit_learn',
        'tensorflow',
        'keras',
        'transformers',
        'sentence_transformers',
        'datasets',
        'accelerate',
        'tokenizers',
        'matplotlib',
        'PIL',
        'bokeh',
        'plotly',
        'seaborn',
        'nltk',
        'spacy',
        'openai',
        'anthropic',
        'paddle',
        'paddleocr',
        'colossalai',
        'tkinter',
        'IPython',
        'jupyter',
        'notebook',
        'nbformat',
        'nbdime',
        'mpl_toolkits',
    ],
    noarchive=False,
    optimize=0,
)
# Bundle the steamcmd *program* only — exclude the steamapps/ download cache
# (downloaded mods, user data), userdata/, and other runtime caches/logs to
# keep the EXE small. Excluded: steamapps (downloaded mods), userdata,
# depotcache (download manifests), appcache (Steam cache), logs, siteserverui
# (unrelated Steam site-server UI), *.old backups and update_hosts_cached.vdf.
a.datas += Tree(
    'steamcmd',
    prefix='steamcmd',
    excludes=[
        'steamapps',
        'userdata',
        'depotcache',
        'appcache',
        'logs',
        'siteserverui',
        'steamcmd_siteserverui_win64.zip*',
        '*.old',
        'update_hosts_cached.vdf',
    ],
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='rwmod',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
